version: 2
updates:

  # Check github actions workflow files
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
    commit-message:
      prefix: “github-actions”
      include: scope
    reviewers:
      - burney95
      - ammarh85

  # Maintain dependencies for multi-lambda-template
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: “pip”
      include: scope
    reviewers:
      - burney95
      - ammarh85
