on: push
name: SonarQube Workflow
jobs:
 sonarqube:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@main
    with:
     fetch-depth: 0
   # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
  - uses: actions/setup-java@v3
    with:
      distribution: 'temurin' # See 'Supported distributions' for available options
      java-version: '17'
    # Setup sonar-scanner
  - name: Setup SonarQube
    uses: warchant/setup-sonar-scanner@v8
    # Run sonar-scanner
  - name: SonarQube Scan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Neeeeeded to get PR information, if any
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    run: sonar-scanner   -Dsonar.projectKey=devscan300   -Dsonar.sources=.   -Dsonar.host.url=http://3.87.178.52:9096   -Dsonar.login=8444a6095845c21e6f8f995ba09b4327856648df
